---
title: "dwii"
author: "Rachel Tao"
date: "10/20/2020"
output: html_document
---
---
title: "Strings and Factors"
author: Rachel Tao
output: github_document

---

```{r setup, include = FALSE}

library(tidyverse)
library(rvest)
library(httr)

knitr::opts_chunk$set(
	fig.asp = 0.6,
	fig.width = 6,
	out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r}
api_url = "https://data.cityofnewyork.us/resource/43nn-pn8j.csv"

rest_inspections =  
  GET(api_url, query = list("$limit" = 50000)) %>% 
  content("parsed")

```


```{r}
rest_inspections %>% 
  count(boro, grade) %>% 
  pivot_wider(names_from = grade, values_from = n)
```


```{r}
rest_inspections = 
  rest_inspections %>% 
  filter(grade %in% c("A", "B", "C"), boro != 0)
```

Let's look at pizza places

```{r}
rest_inspections %>% 
  mutate(dba = str_to_upper(dba)) %>% 
  filter(str_detect(dba, "PIZZ")) %>% 
  count(boro, grade) %>% 
  pivot_wider(names_from = grade, values_from = n)
```

```{r}
rest_inspections %>% 
  mutate(dba = str_to_upper(dba)) %>% 
  filter(str_detect(dba, "PIZZ")) %>% 
  mutate(
    boro = fct_infreq(boro),
    boro = str_replace(boro, "Brooklyn", "Hipsterville") 
  ) %>% 
  ggplot(aes(x = boro)) +
  geom_bar() +
  facet_wrap(. ~ grade)
```

## Napoleon Dynamite

```{r}
nap_dyn_url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

napoleon_html = read_html(nap_dyn_url)

```


